name: Generate Snake

on:
  schedule:
    - cron: "* */24 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: rukasudev
          outputs: dist/snake.svg

      - name: Commit and Push Snake Animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp dist/snake.svg ./snake.svg
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add snake.svg
          git commit -m "Update Snake animation" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
